name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore windows-cs/LangSwitcher.Tests/LangSwitcher.Tests.csproj

      - name: Run Tests and Publish Debug
        run: |
          dotnet publish windows-cs/LangSwitcher.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o windows-cs/out > publish.log 2>&1
          dir windows-cs\out >> publish.log 2>&1
          dotnet test windows-cs/LangSwitcher.Tests/LangSwitcher.Tests.csproj --no-restore --verbosity normal > test.log 2>&1
          if ($LASTEXITCODE -ne 0 -or !(Test-Path windows-cs\out\LangSwitcher.exe)) {
            Write-Host "Test or Publish failed!"
            exit 1
          }

      - name: Upload Debug Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: |
            publish.log
            test.log
